### ISSUE TITLE
удалить лишний код

### ISSUE THREAD

**Issue by LennyLizowzskiy** [LennyLizowzskiy/shikibot#7]
https://github.com/LennyLizowzskiy/shikibot/blob/master/index.ts#L6-L20

**Comment by oplexz** [comment]
предлагаю удалить https://github.com/LennyLizowzskiy/shikibot/blob/master/index.ts#L1-L570
LGTM

**Comment by LennyLizowzskiy** [comment]
https://github.com/LennyLizowzskiy/shikibot/blob/master/tsconfig.json#L8
